# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2ad48101bf2b8feeddcf731c4bde0a0530dc3c4a3c7173e2b09274a06294178079b6199a2ba620a306d4357ae668ba9afd4735ba2b9c24f57223e8fcd7d2e6

test:
  secret_key_base: 3dcd14e6cf09e81125329accffd68330b2ae4b09e00c211264f650d14e99cc2e4f99f855e97805026d1f6f71b94d31da21ffe18a22e0eb4aa1dcc6ee0ed66db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
